### ISSUE TITLE
pymongo issue with replicaset

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/nmdc-runtime#236]
New versions of pymongo don't see to be playing nice with our replicaSet config (works with v 3.12.0 but not with v 4.2.0 and higher).

We should pin Mongo to this version until we've tested. 

To recreate:
```
url = "mongodb://user:pass@mongo-loadbalancer.nmdc.production.svc.spin.nersc.org/admin"

import pymongo
client = pymongo.MongoClient(url)
nmdc = client.nmdc
nmdc.list_collection_names()
```

This fails on production (replicaset) with pymongo 4.2.2 and 4.3.3 
```
ServerSelectionTimeoutError: Could not reach any servers in [('mongo', 27017)]. Replica set is configured with internal hostnames or IPs?, Timeout: 30s, Topology Description: <TopologyDescription id: 641b59ae73464b42eaeb7280, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -2] Name or service not known')>]>
```

It works on dev (which is not replicated)

**Comment by eecavanna** [comment]
When this Issue was created, the Mongo server in "the development environment" (which was the `nmdc-dev` namespace on the **`development`** cluster) **was not** configured as a replica set.

As of June 23, 2023, the Mongo server in "the development environment" (which is now the `nmdc-dev` namespace on the **`production`** cluster) **is** configured as a replica set. 

Here's a screenshot showing some of the environment variables of the `mongo` container in that environment:

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/c9df628d-c543-4ca5-baec-abc3c3ccee5b)

Here's the Python code I use to connect to the `nmdc` database on that server, as of today (with real `host`, `port`, `username`, and `password` values redacted):

```py
from pymongo import MongoClient


# Connect to the Mongo server.
mongo_client = MongoClient(host="host",
                           port="27017",
                           authSource="admin",
                           username="username",
                           password="password",
                           directConnection=True,  # since Mongo is configured as a Replica Set
                           )

# Get a reference to the database.
database_name = "nmdc"
db = mongo_client[database_name]
```
