### ISSUE TITLE
API validation to make sure nmdc identifiers are not duplicated

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#240]
the value for 'id' in mongo should be unique. The APi should validate that submissions don't contain an identifier that has already been used. Example: 
A submission was allowed with duplicate values for 'id' for field_research_site_set
{
    "_id" : ObjectId("641dde3711db7ba4959f2d2b"),
    "id" : "nmdc:frsite-11-s2dqk408",
    "name" : "BESC-470-CL2_38_23"
}
{
    "_id" : ObjectId("641dde3711db7ba4959f2d88"),
    "id" : "nmdc:frsite-11-s2dqk408",
    "name" : "BESC-470-CL2_38_23"
}
{
    "_id" : ObjectId("641dde3711db7ba4959f2e13"),
    "id" : "nmdc:frsite-11-s2dqk408",
    "name" : "BESC-470-CL2_38_23"
}

**Comment by dwinston** [comment]
@aclum how can this situation be reproduced? I see that there are no duplicates now. Was this situation created via direct mongo commands? Or via an API endpoint?

**Comment by dwinston** [comment]
Okay, I see what happened. The logic for ensuring unique indexes depends on detection of a document with an "id" field being present in a non-`system.` collection: https://github.com/microbiomedata/nmdc-runtime/blob/0a79872e1f5e562be7d25be726d0aea224a46389/nmdc_runtime/api/main.py#L325

However, this means that a new (empty) collection added to the schema, e.g. `field_research_site_set` is a recent addition, would not have a unique index set for it until after some documents are added. So, one can add a set of documents with shared IDs and it not be rejected by mongodb as an index integrity violation.

To guard against this, I will

- (a) ensure full simulation of database action during json validation (this is done for changesheets:validate, i.e. a temporary mongodb database is created for each validation request, but not currently for json:validate)
- (b) change the ensure-unique-indexes logic to be sourced from the schema (either directly from the json schema per https://github.com/microbiomedata/nmdc-schema/issues/852 or otherwise pre-computed).

**Comment by dwinston** [comment]
#245 addresses part (b) above.
