### ISSUE TITLE
changesheet failure on mongo-dev with database drop error 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#274]
dagit log:
https://dagit-dev.microbiomedata.org/runs/9561421a-d8d0-4044-8455-b3d56a44fdc5?focusedTime=1688159419550&logFileKey=jdcacgum

error:
dagster._core.definitions.events.Failure: The database is currently being dropped. Database: nmdc_changesheet_submission_results, full error: {'ok': 0.0, 'errmsg': 'The database is currently being dropped. Database: nmdc_changesheet_submission_results', 'code': 215, 'codeName': 'DatabaseDropPending', '$clusterTime': {'clusterTime': Timestamp(1688159418, 1), 'signature': {'hash': b'\x87 \xdc\rY\x0bi\xfei\xbf\x9b\x11lWR_\x00\xd4\xd0p', 'keyId': 7247581269880471557}}, 'operationTime': Timestamp(1688159418, 1)}

**Comment by eecavanna** [comment]
That error occurred on June 30. I checked the table of all runs of the same job (i.e. [the `apply_changesheet` job](https://github.com/microbiomedata/nmdc-runtime/blob/24cc0a6640329a168a55091267e35db0508e8751/nmdc_runtime/site/graphs.py#L99)) and saw a subsequent run succeeded (i.e. run `82c0e1c9`, dated today, July 11). Based on that, I think the cause of the error has either been resolved or is intermittent.

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/7fc965f3-f0e1-4328-b669-7f4a007fc644)

Regarding this part of the error message, which is referring to the Mongo database:
```
The database is currently being dropped. Database: nmdc_changesheet_submission_results
```
According to Rancher, the container running Mongo (in the new development environment) has been running since June 27. The logs for the container only go back to July 9, though (they don't contain information about June 30). I don't know whether that's because they are circular logs that only preserve two days worth, or the container only started logging things two days ago, or due to something else.

**Comment by aclum** [comment]
fixed upon rerunning dagster job.
