### ISSUE TITLE
changsheets inconsistent mechanism for updating multivalued slots 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#284]
I've noticed that depending on the slot you have to fill out changsheets differently when slots are multivalued. For example for slot `websites` on class `biosample` you can enter a changesheet as followings where the first record in the array is added with an `update` action and subsequent values with an `insert` action.

nmdc:sty-11-hht5sb92 update  websites https://www.neonscience.org/

nmdc:sty-11-hht5sb92 insert websites https://data.neonscience.org/data-products/DP1.20281.001

However, for other slots like air_temp_regm on class biosample you have to enter the values with an insert action using a trailing pipe format even if you are only inserting one value.
example
my_biosample_id insert air_temp_regm.has_raw_value freeze-thaw|

It would be good if both formatting options worked consistently.

@bmeluch

**Comment by bmeluch** [comment]
The configuration that finally validated for "air_temp_regm.has_raw_value" was 
`add metadata to EMSL studies 50718 and 50267	nmdc:bsm-11-ax989290	insert	air_temp_regm.has_raw_value	freeze-thaw`
So yes "insert", no pipe
"update" with or without pipe did not validate, even if there was no preexisting value in the slot

**Comment by dwinston** [comment]
Hmm, I notice that [websites](https://w3id.org/nmdc/websites) has a range of [String](https://w3id.org/nmdc/String), whereas [air_temp_regm](https://w3id.org/nmdc/air_temp_regm) has a range of [TextValue](https://w3id.org/nmdc/TextValue), which is a "structured" value.

To "set" a multivalued slot with a structured-value range, you can use the "`update` followed by `insert`s pattern" as with e.g. [websites](https://w3id.org/nmdc/websites), but in this case, use variables to mark the value "nodes" for which you are assigning attribute values. Example:

|id|action|attribute|value|
|-|-|-|-|
|nmdc:bsm-11-ax989290|update|air_temp_regm|regm1|
|regm1||has_raw_value|freeze-thaw|
|nmdc:bsm-11-ax989290,|insert|air_temp_regm|regm2|
|regm2||has_raw_value|burn-thaw|

I hope this helps. Please re-open this issue otherwise.
