### ISSUE TITLE
move nmdc metadata translation code to nmdc-runtime

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-runtime#3]
Move the translation code in `nmdc-metadata/metadata-translation` to the `nmdc-runtime` repo. This will make ETL management easier.

@dwinston I'm putting this in a ticket so that we can reference in a pull request.

**Comment by dwinston** [comment]
The `gold_etl` pipeline currently fails because I haven't added all of its dependencies to [requirements/main.in](https://github.com/microbiomedata/nmdc-runtime/blob/33f1084cccd4cd504c930935c46e6bcd45e47923/requirements/main.in). For example, I currently get a `ModuleNotFoundError: No module named 'git_root'`.

This seems like a good exercise for you @wdduncan to get familiarized with the repo. `make update` will re-fetch dependencies, rebuild pinned-requirements files (e.g. requirements/main.txt), and try installing everything in your virtual env to ensure there are no dependency conflicts. Then, you can `make up-dev` and try running the gold_etl pipeline.
