### ISSUE TITLE
Pin container image version in Spin production environment

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/nmdc-runtime#322]
The production instance of NMDC runtime should be pinned to a specific version to avoid accidental pull / deploy of newer images before they are production ready.

**Comment by eecavanna** [comment]
Related issue: https://github.com/microbiomedata/nmdc-runtime/issues/357

**Comment by eecavanna** [comment]
This change is consistent with a recommendation I see in the Kubernetes documentation, which is:
> ...avoid using the `:latest` tag when deploying containers in production as it is harder to track which version of the image is running and more difficult to roll back properly.
- Source: https://kubernetes.io/docs/concepts/containers/images/

**Comment by dwinston** [comment]
@shreddd @pkalita-lbl

**Comment by eecavanna** [comment]
My perspective (as currently a bystander of this issue): I find the current (a.k.a. new) setup adequate (I like it):
- A: Commit/merge into `main` branch on GitHub 
    - -> publishes new `:main` container image to DockerHub 
    - -> redeploys `nmdc-dev` workloads (which are pinned to `:main`) on Spin
- B: Create a Release on GitHub 
    - -> publishes new `:prod` container image to DockerHub 
    - -> redeploys `nmdc` workloads (which are pinned to `:prod`) on Spin

It makes it so the prod deployments are not affected by event "A" anymore.

**Comment by pkalita-lbl** [comment]
I'm the one who set it up the way it currently is so yeah I'm in favor of it 😁. The intention was to have one less manual step. With the current setup the only manual step is creating the GitHub Release. Everything is automatic after that. The `:prod` tag makes it so that we don't have to manually go into Rancher and point various workloads to different image tags. We still make the `:X.Y.Z` tags, so in the case of an emergency we can rollback by manually going into rancher and pointing to the last releases `:X.Y.Z` tag instead of `:prod`.

**Comment by dwinston** [comment]
okay. I agree. closing this. @shreddd please re-open if you disagree.
