### ISSUE TITLE
Some Napa environment-specific URLs resolve to production environment (as of an 09/2023 commit)

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#442]
See: https://dagit-napa.microbiomedata.org/runs/c3b9b292-7fc4-403d-a0bd-d628f61438a1?focusedTime=1705439489991&logFileKey=suimkuwe
changesheets:submit endpoint works but json:submit endpoint does not. This endpoint is what we are using to add data objects and workflow execution metadata for proteomics.

This is blocking testing proteomics re-iding 
cc @picowatt @corilo @dwinston 

env: napa

**Comment by dwinston** [comment]
It seems that https://api-napa.microbiomedata.org/objects/gfs0we84 redirects to https://api.microbiomedata.org/objects/gfs0we84. The first redirect in the chain is https://w3id.org/nmdc/gfs0we84 (inspecting network requests via Firefox's web developer tools), and I recalled that I had redirected to [w3id.org](http://w3id.org/) for an early implementation of /objects/{object_id} routing in the codebase. Looking at the nmdc-napa namespace in NERSC Spin Rancher, I see the runtime-api workload is pinned to the microbiomedata/nmdc-runtime-fastapi:commit-481ab8e image, whereas the workload in the nmdc-dev namespace is pinned to microbiomedata/nmdc-runtime-fastapi:main. I'd recommend redeploying the nmdc-napa runtime-api workload to use the :main image, but I'll leave that to you, as I don't know if you have some dependency on that version of the runtime at the moment and need to cherry-pick the code changes.

**Comment by dwinston** [comment]
I went ahead and made a `napa` branch (https://github.com/microbiomedata/nmdc-runtime/compare/napa?expand=1) for which I reverted nmdc-schema to 7.8.0, and I pushed tagged images, so that redeploying the napa-namespace workloads using `:napa` images should work.

**Comment by ssarrafan** [comment]
Appears to be active. Moving to next sprint.

**Comment by eecavanna** [comment]
I will move this ticket to the backlog.

The impacted Napa Compliance squad members were able to insert the data data directly into the Napa database, bypassing the Napa Runtime API altogether. For similar data insertion tasks in the future, they will be able to use the standalone Python script, [insert_many_pymongo.py](https://github.com/microbiomedata/nmdc-schema/blob/napa_compliance/nmdc_schema/insert_many_pymongo.py). That script has been [updated](https://github.com/microbiomedata/nmdc-schema/commit/f85d6c6fffd4944d521b0fe3011419ba44220356#diff-38b94d857c09079b46febc7fe16036018647b966c717908e3e655d3712ae26c0R88) to validate the data before inserting it into the database.

Also, @dwinston pointed out on [Slack](https://nmdc-group.slack.com/archives/C05RNEJAV38/p1706114761084799?thread_ts=1705536467.131449&cid=C05RNEJAV38) that, in the latest version of the Runtime API (which is several months newer than the version in use by the Napa Compliance squad), the offending endpoint no longer redirects to `w3id.org`; so, I think the issue has been fixed in the `main` branch and is only occurring here because the squad is using a version from before that fix was implemented. More details are available on [Slack](https://nmdc-group.slack.com/archives/C05RNEJAV38/p1706148688988689?thread_ts=1705536467.131449&cid=C05RNEJAV38). With that in mind, I will update the title of this issue to specify the branch.

**Comment by eecavanna** [comment]
I looked up the Git commit whose hash appears in the container image tag (i.e. `commit-481ab8e`), and found it [here](https://github.com/microbiomedata/nmdc-runtime/commit/481ab8e). The commit was made on September 22, 2023. I have renamed the issue accordingly.

**Comment by aclum** [comment]
Napa is gone, closing.
