### ISSUE TITLE
Consider ISO8601 for datetime which would be much easier to parse and validate across systems

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-runtime#5]
Basically the portal team would like to review with the metadata team the choice of this more difficult to parse datetime. If there are good reasons for this format we can keep it. If there are standard libraries for parsing these somewhat odd timestamps we should utilize them.

**Comment by wdduncan** [comment]
I went through the schema looking for timestamp fields. In MIXS, I found the following fields took dates as values:
```
- fire
- last_clean
- date_last_rain
- iw_bt_date_well
- flooding
- extreme_event
- collection_date
```
Of these terms, only `collection_date` has data values associated with it, and these values are  already form  in `YYYY-MM-DD`.

As for the data that I am pulling in from GOLD, the only fields I found with datetime values were the `add_date` and `mod_date` fields in the `biosample` and `omics_processing` datasets. 

I also exact data for the `omics_processing.completion_date` field, but (currently) there is no data for this field.

**Comment by wdduncan** [comment]
@dwinston I've made the changes to my code, but on the repo you moved the code that was in `metadata-translation/src/bin/lib`. I remember you mentioning something about this ... but where did you move it to?

Once we figure this out we can merge PR https://github.com/microbiomedata/nmdc-runtime/pull/6.

**Comment by dwinston** [comment]
It is now in [metadata-translation/src/bin/lib](https://github.com/microbiomedata/nmdc-runtime/tree/2078951259f84a30784828663ddf2c82c00b02aa/metadata-translation/src/bin/lib) in the nmdc-runtime repo as well.

I had it there in my local repository, but it wasn't under version control because of a conflicting `lib/` entry for Python packaging in the `.gitignore`. I added `!metadata-translation/src/bin/lib` to the `.gitignore` to override this for our directory of interest.

You should be all set now. Let me know if anything else is blocking for you.

**Comment by dwinston** [comment]
I merged in @wdduncan's PR #6. Will close this once the change is propagated for nmdc-server ingest, i.e. will co-close with #2.

**Comment by wdduncan** [comment]
@ssarrafan this is pretty much finished, but waiting on @dwinston to close the ticket. So, I'll move this to the June sprint.

**Comment by dwinston** [comment]
As the code for this is written, and what remains is for the metadata to be re-processed, I think this issue can be closed for now. It should be re-opened if any datetimes are discovered to be improperly encoded.
