### ISSUE TITLE
Cannot find or update documents by `_id` ObjectId via `/queries:run` endpoint

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc-runtime#575]
The overall goal here is to fix malformed workflow ID.versions in the database e.g. `nmdc:wfrbt-11-t0xw3k43.1.1` that were created by a bug in part of the re-ID tool chain.  We would like to be able to do this by submitting to the `queries:run` endpoint.

Description / Steps to Recreate.
Note that I am using the "Napa" instance of our runtime/database 
https://api-napa.microbiomedata.org/docs#/queries/run_query_queries_run_post

Updating a record via `_id`
- request body
```
{
    "update": "read_based_taxonomy_analysis_activity_set",
    "updates": [
        {
            "q": {
                "_id": "6647b8ffe95c3fa0447675bd"
            },
            "u": {
                "$set": {
                    "id": "nmdc:wfrbt-11-t0xw3k43.1"
                }
            }
        },
        {
            "q": {
                "_id": "6647b8ffe95c3fa0447675bd"
            },
            "u": {
                "$addToSet": {
                    "alternative_identifiers": "nmdc:wfrbt-11-t0xw3k43.1.1"
                }
            }
        }
    ]
}
``` 
- curl
```
curl -X 'POST' \
  'https://api-napa.microbiomedata.org/queries:run' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer redacted' \
  -H 'Content-Type: application/json' \
  -d '{
    "update": "read_based_taxonomy_analysis_activity_set",
    "updates": [
        {
            "q": {
                "_id": "6647b8ffe95c3fa0447675bd"
            },
            "u": {
                "$set": {
                    "id": "nmdc:wfrbt-11-t0xw3k43.1"
                }
            }
        },
        {
            "q": {
                "_id": "6647b8ffe95c3fa0447675bd"
            },
            "u": {
                "$addToSet": {
                    "alternative_identifiers": "nmdc:wfrbt-11-t0xw3k43.1.1"
                }
            }
        }
    ]
}'
``` 
- response
```
{
  "detail": [
    "update command modified zero documents. I'm guessing that's not what you expected. Check the syntax of your request. But what do I know? I'm just a teapot."
  ]
}
``` 

Finding Records based on `_id`
- Request body
```
{
    "find": "read_based_taxonomy_analysis_activity_set",
    "filter": {"_id": "6647b8ffe95c3fa0447675bd"}
}

``` 
- Response
```
{
  "ok": 1,
  "cursor": {
    "firstBatch": [],
    "partialResultsReturned": null,
    "id": 0,
    "ns": "nmdc.read_based_taxonomy_analysis_activity_set"
  }
}
```

**Comment by eecavanna** [comment]
I checked [the endpoint's code](https://github.com/microbiomedata/nmdc-runtime/blob/69bf65425e3ee0dc336a8b16080f583dccb3ce10/nmdc_runtime/api/endpoints/queries.py#L41) and didn't notice any special handling for the `_id` field.

I assume the Runtime is not converting the submitted string into an `ObjectId` instance before sending the query to Mongo.

That conversion step is referenced in the [pymongo docs](https://pymongo.readthedocs.io/en/stable/faq.html#when-i-query-for-a-document-by-objectid-in-my-web-application-i-get-no-result). In those docs, its absence is referred to as a "common mistake." I don't know whether it was a mistake in this case or it was done (er... not done) intentionally. If it was intentional, I would recommend that that user-impacting limitation (i.e. "cannot filter by _id") be documented in the API endpoint's documentation (i.e. docstring) that appears on the Swagger UI.

**Comment by mbthornton-lbl** [comment]
Is blocking:
https://github.com/microbiomedata/nmdc_automation/issues/198

**Comment by dwinston** [comment]
@mbthornton-lbl why not run e.g.

```json
{
  "update": "read_based_taxonomy_analysis_activity_set",
  "updates": [{
    "q": {"id": "nmdc:wfrbt-11-t0xw3k43.1.1"},
    "u": {
      "$set": {"id": "nmdc:wfrbt-11-t0xw3k43.1"},
      "$addToSet": {"alternative_identifiers": "nmdc:wfrbt-11-t0xw3k43.1.1"}
    }}]
}
```

? I ran this against https://api-dev.microbiomedata.org/ and it seemed to work. Additional advantage: the two tasks of re-setting `id` and adding to `alternative_identifiers` are done atomically in one update operation.

I'd rather that only documented NMDC Schema slots be addressable via `/queries:run` queries, i.e. even though it adopts MongoDB syntax for transparency, the intent is not "manipulate the raw Mongo database".

Would this work for you? It seems you will always know the target document's currrent `id`.

**Comment by dwinston** [comment]
I assume this is no longer an issue based on @aclum’s update in Slack.

**Comment by aclum** [comment]
It would still be nice to have this supported, we are not "manipulating the raw Mongo database", just using it to find records. It is confusing and not intuitive that operations that can be handled by pymongo or mongosh aren't supported via queries:run.

**Comment by eecavanna** [comment]
> even though it adopts MongoDB syntax for transparency

I think I see where @dwinston is coming from here. I don't know that the Runtime exposes the `_id` values to consumers of the Runtime API. For example, I checked the objects returned by `GET /studies` and they didn't include `_id` fields. Allowing API consumers to use it might create a conceptual leak (an additional conceptual leak?) in some abstraction (an abstraction in which the fact that the Runtime uses a Mongo database under the hood is an "internal implementation detail" of the Runtime).

**Comment by shreddd** [comment]
Hmm - I don't love the idea of using the internal Mongo IDs in the API since we would typically just use the NMDC ID. I would prefer not to have these IDs be public to end users of the API. Note that these are not guaranteed to be the same if we have to manipulate the DB and create new objects during a migration etc.  

That said, if this is useful for internal privileged users like Michael, to deal with buggy NMDC IDs we can consider a workaround or bypass for the direct mongo query endpoint.

**Comment by aclum** [comment]
Closing as won't fix.
