### ISSUE TITLE
Dagster `apply_metadata_in` op fails to insert `functional_annotation_agg` documents

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#611]
**Describe the bug**
I tried to submit test data to runtime dev for the functional_annotation_agg, the data validates with `json:validate` and returns all okay with `json:submit` but the dagster job fails. Based on the issue see https://dagit-dev.microbiomedata.org/runs/76495c80-9076-4da4-94e5-4baf162a1d6d

```py
KeyError: 'functional_annotation_agg'
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/opt/dagster/lib/nmdc_runtime/site/ops.py", line 530, in perform_mongo_updates
    if all(coll_has_id_index[coll] for coll in docs.keys()):
  File "/opt/dagster/lib/nmdc_runtime/site/ops.py", line 530, in <genexpr>
    if all(coll_has_id_index[coll] for coll in docs.keys()): 
```

**To Reproduce**
1. go to runtime dev & login with personal credentials
2. Submit request (see snippet below)

```shell
curl -X 'POST' \
  'https://api-dev.microbiomedata.org/metadata/json:submit' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer $TOKEN' \
  -H 'Content-Type: application/json' \
  -d '{"functional_annotation_agg":[
{"metagenome_annotation_id":"nmdc:wfmtan-13-hemh0a82.1",
"gene_function_id": "KEGG.ORTHOLOGY:K00005",
"count":10},
{"metagenome_annotation_id":"nmdc:wfmtan-13-hemh0a82.1",
"gene_function_id": "KEGG.ORTHOLOGY:K01426",
"count":5}
]}'
```
3. go to https://dagit-dev.microbiomedata.org/locations/repo@nmdc_runtime.site.repository%3Arepo/jobs/apply_metadata_in to check on status

**Expected behavior**
This request should return records
```shell
curl -X 'GET' \
  'https://api-dev.microbiomedata.org/nmdcschema/functional_annotation_agg?filter=%7B%22metagenome_annotation_id%22%3A%22nmdc%3Awfmtan-13-hemh0a82.1%22%7D&max_page_size=20' \
  -H 'accept: application/json'
```

Example user story template:
AS A {user|persona|system},
[INSTEAD OF {current condition}]
I EXPECTED {result}
[SO THAT {value or justification}]
[NO LATER THAN {best by date}]

**Screenshots**

**Acceptance Criteria**
- Clear to everyone involved
- Can be tested or verified 
- Either passes or fails (cannot be 50% completed, for example)
- Focus on the outcome, not how the outcome is achieved
- As specific as possible (fast page load speed vs. 3-second page load speed)
- if multiple criteria, present as a bulleted list of short scenarios (see template below)

Example scenario-based template:
Given (some given context or precondition), when (I take this action), then (this will be the specific outcome).

**Additional context**
I think this is b/c those documents don't have id, normally these records are added directly to pymongo by code from [nmdc-aggregator](https://github.com/microbiomedata/nmdc-aggregator)

**Comment by eecavanna** [comment]
@aclum and I met via Zoom a few minutes ago. She explained the situation for me and showed me where I can find the error message in the Dagster UI (Dagit).

Since this is the development environment—not the production environment—in order to unblock what she is working on (which is to enable someone else downstream), I was in favor of adding the documents to the database directly (via the Mongo root account). I want to emphasize that this was in the development environment.

So, I did that during the Zoom call; i.e. I added the two documents to the database. As a result, @aclum's work is not blocked by this issue.

I will continue looking into this issue.

**Comment by eecavanna** [comment]
Here's the final couple of lines from the stack trace:

```py
  File "/opt/dagster/lib/nmdc_runtime/site/ops.py", line 530, in <genexpr>
    if all(coll_has_id_index[coll] for coll in docs.keys()):
```

Here are lines 529-531 of the source code the error message is referring to:

```py
    coll_has_id_index = collection_indexed_on_id(mongo.db)
    if all(coll_has_id_index[coll] for coll in docs.keys()):
        replace = True
```
> Source: [nmdc-runtime](https://github.com/microbiomedata/nmdc-runtime/tree/31b039831698a9b40d25ed699517d39f28357581)/[nmdc_runtime](https://github.com/microbiomedata/nmdc-runtime/tree/31b039831698a9b40d25ed699517d39f28357581/nmdc_runtime)/[site](https://github.com/microbiomedata/nmdc-runtime/tree/31b039831698a9b40d25ed699517d39f28357581/nmdc_runtime/site)/[ops.py](https://github.com/microbiomedata/nmdc-runtime/blob/31b039831698a9b40d25ed699517d39f28357581/nmdc_runtime/site/ops.py#L529C1-L531C23)

Note that the first line of that source code calls a function named `collection_indexed_on_id` (I don't know why the name is a noun instead of a verb). Based on its name, I assume it returns collections, or names of collections, that have an index on their `id` field.

The collection @aclum was trying to insert data into is `functional_annotation_agg`. Documents in that collection do not have an `id` field. So, I doubt the collection has an index on its `id` field.

**Comment by eecavanna** [comment]
Since I'll be OOO for the next few days (back next Wednesday), I'll hand this issue off to @dwinston and @PeopleMakeCulture.

**Comment by eecavanna** [comment]
Looks like the `collection_indexed_on_id` only accounts for [functions](https://github.com/microbiomedata/nmdc-runtime/blob/31b039831698a9b40d25ed699517d39f28357581/nmdc_runtime/site/util.py#L37-L43) whose names end in `_set`. That design decision is not documented in the source code and I don't know the implications of changing it, on the rest of the code base.

**Comment by aclum** [comment]
@PeopleMakeCulture any update on this?
