### ISSUE TITLE
Add github actions to check PRs

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-runtime#65]
I think this is a required part of #56 

We have github actions but it seems they are just for deployment, they don't check PRs, I did an experiment here:

#64

This introduced a deliberate error yet I am still able to merge:

![image](https://user-images.githubusercontent.com/50745/139742307-c100a2ad-cbf3-4c39-a91f-f4c1bf8bda71.png)

**Comment by dwinston** [comment]
@elais this could be a good one for you -- setting up a GH action to run `pytest` to check PRs.

**Comment by elais** [comment]
Right now the github action has a installing dependencies, which I guess is why it was dismantled in the first place. I did add a change to make sure the test environment tries to build on each pull request (for testing) but it's not yet set up to halt a pull if the action fails.

Was there a reason the actions were disabled to begin with? Maybe because of that failing dependency?

**Comment by elais** [comment]
I made a change but someone with more permissions than me needs to set up protections on the branches. It's not a long process and since this project is visible to the public I don't think it will be a problem to run this on pull requests to every branch.
![image](https://user-images.githubusercontent.com/2111879/139774732-b3306781-8156-4136-8b83-8785410dd8d4.png)

**Comment by cmungall** [comment]
Reopening as things don't seem to work yet - unless main is in a fail state?

I did a test PR #69 

Which is a null change, actions fail

**Comment by elais** [comment]
Getting the tests running was the task. Actually passing them should be a new issue, IMO.

**Comment by elais** [comment]
Just did a check and while my merge of the task fpassed it looks like every subsequent push by @dwinston has failed the tests. I'm not sure what he's up to but it looks like he's been introducing breaking changes.

I'm closing this again because the problem @cmungall sees is out of scope.
