### ISSUE TITLE
`berkeley` test_apply_metadata_in_functional_annotation_agg pytest failure

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#679]
Based on the error message we need to add type and bump the version of the schema to a version that allows for metatranscriptome IDs.

**Comment by eecavanna** [comment]
This ticket is listed as a "Fixes" item in PR #676. Also, that PR does update the schema version and the author of this ticket mentioned updating the schema version as something we would need to do. For those reasons (mostly the first one), I'll close this issue.

I think GitHub doesn't automatically close it because the base branch of the PR was not `main` (it was `berkeley`).
