### ISSUE TITLE
`berkeley`: Restore hyperlinks to "Metadata" section and  modernize Runtime description

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#685]
- [x] hyperlinks are not working in the metadata endpoint section (studies, biosamples, planned processes, and data objects)
- [x] In the main description update 'The NMDC Runtime API, via on-demand functions and via schedule-based and sensor-based automation, supports validation and submission of metadata, as well as orchestration of workflow execution activities.' to 'The NMDC Runtime API, via on-demand functions and via schedule-based and sensor-based automation, supports validation and submission of metadata, as well as orchestration of workflow executions.'
cc @brynnz22

**Comment by eecavanna** [comment]
Thanks for reviewing and reporting those things. I'll fix them after 3pm PT today. @PeopleMakeCulture, you are welcome to implement these fixes in the meantime, in case you happen to be work on this repo between now and then.

**Comment by eecavanna** [comment]
I'll fix these now.

**Comment by eecavanna** [comment]
> hyperlinks are not working in the metadata endpoint section (studies, biosamples, planned processes, and data objects)

I looked into this. Those words are, indeed, hyperlinks on the production Runtime (where "activities" is listed instead of "planned processes"). They are not hyperlinks on the Berkeley Runtime (as reported in this Issue).

The are not hyperlinks in the legacy API GUI how-guide _or_ the Berkeley API GUI how-to guide (the latter is what I copy/pasted the content from yesterday, for PR https://github.com/microbiomedata/nmdc-runtime/pull/682).

![image](https://github.com/user-attachments/assets/412556cf-f5f3-49fa-bec7-b7966e0dc35d)

So, I assume a Runtime developer added the links to the Runtime by hand at some point. I will do the same now.

**Comment by eecavanna** [comment]
Fixed in PR https://github.com/microbiomedata/nmdc-runtime/pull/686 (ready for review).
