### ISSUE TITLE
API endpoint `"/nmdcschema/{collection_name}"` takes 4x longer when using pagination (with `functional_annotation_agg`)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#797]
The following HTTP request currently takes 1.2 minutes to complete in the dev environment:

```sh
curl -X 'GET' \
  'https://api-dev.microbiomedata.org/nmdcschema/functional_annotation_agg?filter=%7B%22was_generated_by%22%3A%7B%22%24regex%22%3A%22wfmp%22%7D%7D&max_page_size=50&projection=was_generated_by' \
  -H 'accept: application/json'
```
> Notice: The `max_page_size` is `50` (i.e. not `0`).

Here's a screenshot showing the same parameter values entered into Swagger UI:

<img width="392" alt="image" src="https://github.com/user-attachments/assets/ae5c4876-da21-48b2-93f3-3f6f2d53b2ef">

In contrast, the following HTTP request currently takes 0.3 minutes to complete in the dev environment:

```sh
curl -X 'GET' \
  'https://api-dev.microbiomedata.org/nmdcschema/functional_annotation_agg?filter=%7B%22was_generated_by%22%3A%7B%22%24regex%22%3A%22wfmp%22%7D%7D&max_page_size=0&projection=was_generated_by' \
  -H 'accept: application/json'
```
> Notice: The `max_page_size` is `0`.

I suspect the issue is related to the fact that the function that powers that endpoint does different things depending upon whether `max_page_size` is `0` or not `0`, as shown below. I notice, in the case of the former, the Mongo querying code does not use the `sort`, `limit`, or `allow_disk_use` kwargs.

https://github.com/microbiomedata/nmdc-runtime/blob/d7da63fdfaf9262ad1da4d0d9c4301b8d119b534/nmdc_runtime/api/endpoints/util.py#L104-L134

Thank you, @kheal, for reporting this issue. In the case of what she was working on today, setting `max_page_size=0` was a sufficient workaround. In other cases, it may not be (e.g. when the response would contain more data than some piece of our infrastructure—or the requesting HTTP client—supports).

**Comment by eecavanna** [comment]
Reopening. Although the `was_generated_by` index now exists in the development database, the original symptom persists.

**Comment by eecavanna** [comment]
Here are the times I measured today, with the `was_generated_by` index in place.

This request/response cycle, with `max_page_size=50`, took 1 minute and 34 seconds to complete:

```shell
date && curl -X 'GET' \
  'https://api-dev.microbiomedata.org/nmdcschema/functional_annotation_agg?filter=%7B%22was_generated_by%22%3A%7B%22%24regex%22%3A%22wfmp%22%7D%7D&max_page_size=50&projection=was_generated_by' \
  -H 'accept: application/json' --max-time 180 && date
```

This request/response cycle, with `max_page_size=0`, took 23 seconds to complete:

```shell
date && curl -X 'GET' \
  'https://api-dev.microbiomedata.org/nmdcschema/functional_annotation_agg?filter=%7B%22was_generated_by%22%3A%7B%22%24regex%22%3A%22wfmp%22%7D%7D&max_page_size=0&projection=was_generated_by' \
  -H 'accept: application/json' && date
```

I expect an index to help with operations that involve search for documents by the values in their `was_generated_by` fields, so I don't have any concerns about it existing. It does not seem to me to impact this particular issue, though.

**Comment by dwinston** [comment]
@eecavanna the following took 6 seconds to complete:

```bash
date && curl -X 'GET' \
  'https://api-dev.microbiomedata.org/nmdcschema/functional_annotation_agg?filter=%7B%22was_generated_by%22%3A%20%7B%22%24regex%22%3A%20%22%5Enmdc%3Awfmp%22%7D%7D&max_page_size=50&projection=was_generated_by' \
  -H 'accept: application/json' --max-time 180 && date
```

The difference is that the above percent-encodes a `filter` of `{"was_generated_by": {"$regex": "^nmdc:wfmp"}}`, whereas the slow `filter` is `{"was_generated_by": {"$regex": "wfmp"}}`. The former uses a so-called "prefix expression" with `$regex`, which can result in *substantially* more performant queries on a large collection such as "functional_annotation_agg", which has nearly 28M documents.

As I noted in https://github.com/microbiomedata/nmdc-aggregator/pull/27#discussion_r1861267629, from <https://www.mongodb.com/docs/v6.0/reference/operator/query/regex/#index-use>:

> Further optimization can occur if the regular expression is a "prefix expression", which means that all potential matches start with the same string. This allows MongoDB to construct a "range" from that prefix and only match against those values from the index that fall within that range.
> 
> A regular expression is a "prefix expression" if it starts with a caret (^) or a left anchor (\A), followed by a string of simple symbols. For example, the regex /^abc.*/ will be optimized by matching only against the values from the index that start with abc.

I should note that this issue highlights the challenge of letting API users supply "full power" mongo query expressions, which historically has not been of practical concern because none of the schema-defined collections were very large prior to "functional_annotation_agg".

On the role of `allow_disk_use`, it is only relevant when `sort`ing, which in turn is only relevant for `GET /nmdcschema/{collection_name}` when you need or wish to return matching documents using more than a single request/response. The alternative technique for paging, using `skip`+`limit`, results in slower and slower "next-page" responses for large (> 10k document) collections, as `skip` increases and requires "one-at-a-time" iteration over the collection.

**Comment by eecavanna** [comment]
Thanks, @dwinston. I'll reopen and assign to myself. I would like to act upon this recommendation in the user-facing documentation of this endpoint, via a PR tied to this ticket:

> Please update the relevant docstrings to reflect this. We should encourage this optimization for large collections.
