### ISSUE TITLE
Uploading too many metadata-in can swamp the server

### ISSUE THREAD

**Issue by scanon** [microbiomedata/nmdc-runtime#81]
I tried ingesting a lot of annotation/feature records from dozens of metaG's at the same time and it crashed the server.  So we need to see if there is some way to rate limit things in dagster or some alternate method.  I suspect the issue was with memory and doing all the schema validation at the same time.

**Comment by dwinston** [comment]
@scanon this may be correlated with continued use of the Spin development cluster rather than the production cluster.

Can you elaborate on your procedure that resulted in a crash? One possible procedure: you POSTed to /objects N times, and then you PUTted to /objects/{object_id}/types N times. Is this correct?

**Comment by dwinston** [comment]
We should migrate to the production cluster either way, for higher memory capacity.

**Comment by dwinston** [comment]
Migrated “dev” workloads to Spin production cluster. No reports of similar issue since.
